export const PART_CATEGORIES = {
  Fluids: [
    "Synthetic Oil",
    "Conventional Oil",
    "Synthetic Blend Oil",
    "Brake Fluid",
    "Transmission Fluid",
    "Differential Fluid",
    "Power Steering Fluid",
    "Coolant / Antifreeze",
  ],
  Engine: [
    "Gaskets & Seals",
    "Belts & Hoses",
    "Sensors",
    "Spark Plugs",
    "Ignition Coils",
    "Valves",
    "Lifters",
    "Rockers",
    "Pushrods",
    "Camshafts",
    "VVT Solenoids",
    "Timing",
    "Pistons & Rings",
  ],
  Transmission: [
    "Clutch Components",
    "Torque Converters",
    "Input Shafts",
    "Oil Pumps",
    "Planetary Gearsets",
    "Valve Bodies",
    "Transmission Mounts",
    "Bell Housings",
    "Bell Housing Bolts",
    "Flywheels",
    "Flexplates",
    "Slave Cylinders",
    "Pilot Bearings",
    "Clutch Release/Throwout Bearings",
    "Shift Solenoids",
    "Governors",
    "Shift Kits",
    "Output Shafts",
  ],
  "Steering & Suspension": [
    "Ball Joints",
    "Tie Rods",
    "Control Arms",
    "Torsion Rods",
    "Shock Mounts",
    "Shocks & Struts",
    "Bushings",
    "Wheel Bearings",
    "Sway Bar Links",
    "Springs",
  ],
  Brakes: [
    "Brake Pads",
    "Brake Rotors",
    "Brake Drums",
    "Brake Shoes",
    "Brake Calipers",
    "Wheel Cylinders",
    "Brake Lines",
    "Brake Hoses",
    "Slide Pins",
    "Slide Pin Boots",
    "Caliper Brackets",
    "Brake Hardware",
    "Parking Brake",
    "ABS Module Assemblies",
    "ABS Sensors",
    "ABS Hydraulic Units",
    "ABS Control Modules",
  ],
  Filters: [
    "Oil Filter",
    "Engine Air Filter",
    "Cabin Air Filter",
    "Fuel Filter",
    "Transmission Filter",
    "Diesel Particulate Filter",
  ],
  Electrical: [
    "Batteries (Lead-Acid)",
    "Batteries (Lithium-Ion)",
    "Batteries (AGM)",
    "Voltage Regulators",
    "Alternators",
    "Starters",
    "Starter Solenoids",
    "Fuses",
    "Relays",
    "Wiring Harnesses",
    "Ignition Switches",
    "Keys & Fobs",
    "Window Switches",
    "Door Lock Switches",
    "Power Seat Switches",
    "Power Mirror Switches",
    "Power Window Motors",
    "Power Door Lock Actuators",
    "Power Seat Motors",
    "Power Mirror Motors",
    "Lighting Switches",
    "Clock Springs",
    "Speedometers/Instrument Clusters",
    "Connectors",
    "Sensors",
    "Switches",
  ],
  Exterior: [
    "Bumpers",
    "Mirrors",
    "Headlights",
    "Taillights",
    "Turn Signals",
    "Side Markers",
    "Fog Lights",
    "Windshields",
    "Door Glass",
    "Quarter Glass",
    "Sunroof Glass",
    "Grilles",
    "Spoilers",
    "Exterior Door Handles",
    "Body Panels",
    "Trim & Molding",
  ],
  "Interior Trim": [
    "Seat Covers",
    "Floor Mats",
    "Dashboard",
    "Door Panels",
    "Headliner",
    "Sun Visors",
    "Center Consoles",
    "Armrests",
    "Interior Door Handles",
    "Interior Trim Panels",
    "Interior Lighting",
    "Door Panels",
    "Interior Mirrors",
    "Seat Belts",
    "Airbags",
    "Window Regulators",
    "Sunroof Regulators",
  ],
  "Radio & Navigation": [
    "Head Units",
    "Speakers",
    "Amplifiers",
    "Antennas",
    "Backup Cameras",
    "Wiring Harnesses",
  ],
  HVAC: [
    "A/C Compressors",
    "Condensers",
    "Evaporators",
    "Heater Cores",
    "Blower Motors",
    "Refrigerant",
  ],
  Misc: ["Hardware", "Adhesives", "Chemicals", "Shop Consumables"],
};

export const CATEGORY_NAMES = Object.keys(PART_CATEGORIES);

export const getSubcategories = (category: string): string[] =>
  (PART_CATEGORIES as Record<string, string[]>)[category] ?? [];
