export const PART_CATEGORIES = {
  Lubricants: [
    "Synthetic Oil",
    "Conventional Oil",
    "Synthetic Blend Oil",
    "Brake Fluid",
    "Transmission Fluid",
    "Differential Fluid",
    "Power Steering Fluid",
    "Coolant / Antifreeze",
  ],
  Engine: [
    "Gaskets & Seals",
    "Belts & Hoses",
    "Sensors",
    "Spark Plugs",
    "Ignition",
    "Valvetrain",
    "Timing",
    "Pistons & Rings",
  ],
  Transmission: [
    "Clutch Components",
    "Torque Converter",
    "Solenoids",
    "Shift Kits",
    "Output Shafts",
  ],
  "Steering & Suspension": [
    "Ball Joints",
    "Tie Rods",
    "Control Arms",
    "Shocks & Struts",
    "Wheel Bearings",
    "Sway Bar Links",
    "Springs",
  ],
  Brakes: [
    "Brake Pads",
    "Brake Rotors",
    "Brake Calipers",
    "Brake Lines & Hoses",
    "Brake Hardware",
    "Parking Brake",
  ],
  Filters: [
    "Oil Filter",
    "Engine Air Filter",
    "Cabin Air Filter",
    "Fuel Filter",
    "Transmission Filter",
  ],
  Electrical: [
    "Batteries",
    "Alternators",
    "Starters",
    "Fuses & Relays",
    "Wiring & Connectors",
    "Sensors & Switches",
  ],
  Exterior: [
    "Bumpers",
    "Mirrors",
    "Lights & Lighting",
    "Glass & Windshields",
    "Body Panels",
    "Trim & Molding",
  ],
  "Interior Trim": [
    "Seat Covers",
    "Floor Mats",
    "Dashboard",
    "Door Panels",
    "Headliner",
    "Sun Visors",
  ],
  "Radio & Navigation": [
    "Head Units",
    "Speakers",
    "Amplifiers",
    "Antennas",
    "Backup Cameras",
    "Wiring Harnesses",
  ],
  HVAC: [
    "A/C Compressors",
    "Condensers",
    "Evaporators",
    "Heater Cores",
    "Blower Motors",
    "Refrigerant",
  ],
  Misc: ["Hardware", "Adhesives", "Chemicals", "Shop Consumables"],
};

export const CATEGORY_NAMES = Object.keys(PART_CATEGORIES);

export const getSubcategories = (category) => PART_CATEGORIES[category] ?? [];
