export const PART_CATEGORIES = {
  Fluids: [
    "Synthetic Oil",
    "Conventional Oil",
    "Synthetic Blend Oil",
    "Brake Fluid",
    "Transmission Fluid",
    "Differential Fluid",
    "Power Steering Fluid",
    "Coolant / Antifreeze",
  ],
  Engine: [
    "Gaskets & Seals",
    "Belts & Hoses",
    "Sensors",
    "Spark Plugs",
    "Ignition Coils",
    "Valves",
    "Lifters",
    "Rockers",
    "Pushrods",
    "Camshafts",
    "VVT Solenoids",
    "Timing",
    "Pistons & Rings",
    "Engine Mounts",
    "Crankshafts",
    "Connecting Rods",
    "Oil Pans",
    "Valve Covers",
    "Intake Manifolds",
  ],
  "Cooling System": [
    "Water Pumps",
    "Radiators",
    "Thermostats",
    "Radiator Caps",
    "Coolant Hoses",
    "Coolant Overflow Tanks",
    "Fan Clutches",
    "Electric Cooling Fans",
    "Intercoolers",
    "Oil Coolers",
    "Radiator Mounts",
  ],
  "Fuel System": [
    "Fuel Pumps",
    "Fuel Injectors",
    "Fuel Pressure Regulators",
    "Fuel Rails",
    "Fuel Tanks",
    "Fuel Lines",
    "Fuel Sending Units",
    "Mass Air Flow Sensors",
    "Throttle Bodies",
    "Carburetors",
    "Fuel Caps",
    "Induction Kits",
  ],
  Exhaust: [
    "Catalytic Converters",
    "Exhaust Manifolds",
    "Headers",
    "Mufflers",
    "Resonators",
    "Flex Pipes",
    "Exhaust Pipes",
    "Exhaust Tips",
    "Exhaust Hangers",
    "Exhaust Gaskets",
  ],
  Emissions: [
    "O2 Sensors",
    "EGR Valves",
    "EGR Coolers",
    "PCV Valves",
    "EVAP Purge Solenoids",
    "EVAP Canisters",
    "Air Injection Pumps",
    "DEF Systems",
    "Smog Pumps",
  ],
  Transmission: [
    "Clutch Components",
    "Torque Converters",
    "Input Shafts",
    "Oil Pumps",
    "Planetary Gearsets",
    "Valve Bodies",
    "Transmission Mounts",
    "Bell Housings",
    "Bell Housing Bolts",
    "Flywheels",
    "Flexplates",
    "Slave Cylinders",
    "Pilot Bearings",
    "Clutch Release/Throwout Bearings",
    "Shift Solenoids",
    "Governors",
    "Shift Kits",
    "Output Shafts",
    "Transmission Filters",
  ],
  Drivetrain: [
    "CV Axles",
    "CV Joints",
    "CV Boots",
    "U-Joints",
    "Driveshafts",
    "Transfer Cases",
    "Differentials",
    "Axle Shafts",
    "Differential Covers",
    "Axle Seals",
    "Axle Bearings",
    "Ring & Pinion Gears",
    "Locking Hubs",
    "Slip Yokes",
  ],
  "Steering & Suspension": [
    "Ball Joints",
    "Tie Rods",
    "Control Arms",
    "Torsion Rods",
    "Shock Mounts",
    "Shocks & Struts",
    "Bushings",
    "Wheel Bearings",
    "Sway Bar Links",
    "Sway Bar Bushings",
    "Springs",
    "Strut Mounts",
    "Steering Racks",
    "Steering Gear Boxes",
    "Power Steering Pumps",
    "Power Steering Hoses",
    "Steering Columns",
    "Idler Arms",
    "Pitman Arms",
    "Center Links",
  ],
  Brakes: [
    "Brake Pads",
    "Brake Rotors",
    "Brake Drums",
    "Brake Shoes",
    "Brake Calipers",
    "Wheel Cylinders",
    "Brake Lines",
    "Brake Hoses",
    "Master Cylinders",
    "Brake Boosters",
    "Proportioning Valves",
    "Slide Pins",
    "Slide Pin Boots",
    "Caliper Brackets",
    "Brake Hardware",
    "Parking Brake",
    "ABS Module Assemblies",
    "ABS Sensors",
    "ABS Hydraulic Units",
    "ABS Control Modules",
  ],
  "Tires & Wheels": [
    "Tires",
    "Wheels / Rims",
    "TPMS Sensors",
    "Hub Caps / Wheel Covers",
    "Valve Stems",
    "Lug Nuts",
    "Lug Bolts",
    "Hub Assemblies",
    "Center Caps",
  ],
  Filters: [
    "Oil Filter",
    "Engine Air Filter",
    "Cabin Air Filter",
    "Fuel Filter",
    "Transmission Filter",
    "Diesel Particulate Filter",
  ],
  Electrical: [
    "Batteries (Lead-Acid)",
    "Batteries (Lithium-Ion)",
    "Batteries (AGM)",
    "Voltage Regulators",
    "Alternators",
    "Starters",
    "Starter Solenoids",
    "Fuses",
    "Relays",
    "Wiring Harnesses",
    "Ignition Switches",
    "Keys & Fobs",
    "Window Switches",
    "Door Lock Switches",
    "Power Seat Switches",
    "Power Mirror Switches",
    "Power Window Motors",
    "Power Door Lock Actuators",
    "Power Seat Motors",
    "Power Mirror Motors",
    "Lighting Switches",
    "Clock Springs",
    "Speedometers/Instrument Clusters",
    "Connectors",
    "Sensors",
    "Switches",
    "Body Control Modules",
    "PCMs / ECMs",
    "TCMs",
  ],
  "Wipers & Washers": [
    "Wiper Blades",
    "Wiper Arms",
    "Wiper Motors",
    "Wiper Transmission",
    "Washer Pumps",
    "Washer Fluid Reservoirs",
    "Washer Nozzles",
  ],
  Exterior: [
    "Bumpers",
    "Mirrors",
    "Headlights",
    "Taillights",
    "Turn Signals",
    "Side Markers",
    "Fog Lights",
    "Windshields",
    "Door Glass",
    "Quarter Glass",
    "Sunroof Glass",
    "Grilles",
    "Spoilers",
    "Exterior Door Handles",
    "Body Panels",
    "Fenders",
    "Hoods",
    "Trunk Lids",
    "Tailgates",
    "Running Boards",
    "Trim & Molding",
    "Mud Flaps",
    "Tow Hitches",
  ],
  "Interior Trim": [
    "Seat Covers",
    "Floor Mats",
    "Cargo Liners",
    "Dashboard",
    "Door Panels",
    "Headliner",
    "Sun Visors",
    "Center Consoles",
    "Armrests",
    "Interior Door Handles",
    "Interior Trim Panels",
    "Interior Lighting",
    "Interior Mirrors",
    "Seat Belts",
    "Airbags",
    "Window Regulators",
    "Sunroof Regulators",
  ],
  "Radio & Navigation": [
    "Head Units",
    "Speakers",
    "Amplifiers",
    "Antennas",
    "Backup Cameras",
    "Wiring Harnesses",
  ],
  HVAC: [
    "A/C Compressors",
    "Condensers",
    "Evaporators",
    "Heater Cores",
    "Blower Motors",
    "Refrigerant",
    "Expansion Valves",
    "A/C Lines & Hoses",
    "A/C Driers / Accumulators",
    "Blend Door Actuators",
    "Heater Control Valves",
  ],
  Misc: [
    "Hardware",
    "Adhesives",
    "Chemicals",
    "Shop Consumables",
    "Touch-Up Paint",
    "Decals & Emblems",
  ],
};

export const CATEGORY_NAMES = Object.keys(PART_CATEGORIES);

export const getSubcategories = (category: string): string[] =>
  (PART_CATEGORIES as Record<string, string[]>)[category] ?? [];
